run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - misspell
    - unconvert
    - gosec
  disable:
    - exhaustive
    - exhaustruct

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  misspell:
    locale: US

  gosec:
    excludes:
      - G301
      - G302
      - G304
      - G306
      - G104

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    - path: examples/
      linters:
        - errcheck
        - gosec

    - path: pkg/rabbit/
      linters:
        - errcheck

  max-issues-per-linter: 50
  max-same-issues: 10


